import { Document, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
/* eslint-disable @typescript-eslint/no-explicit-any */

const s = StyleSheet.create({ page: { padding: 34, fontFamily: "Helvetica", color: "#18332d", fontSize: 9 }, header: { flexDirection: "row", justifyContent: "space-between", paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: "#1f5a4c" }, brand: { fontSize: 14, fontWeight: 700 }, title: { fontSize: 18, fontWeight: 700, textAlign: "right" }, muted: { color: "#647a72", lineHeight: 1.45 }, block: { marginTop: 16, padding: 12, backgroundColor: "#f4f7f5", flexDirection: "row", justifyContent: "space-between", gap: 18 }, section: { marginTop: 18 }, sectionTitle: { fontSize: 10, fontWeight: 700, marginBottom: 8, textTransform: "uppercase" }, row: { flexDirection: "row", borderBottomWidth: .5, borderBottomColor: "#dce4df", paddingVertical: 6 }, wide: { width: "34%" }, cell: { width: "11%", textAlign: "right" }, code: { width: "13%" }, footer: { position: "absolute", bottom: 22, left: 34, right: 34, borderTopWidth: .5, borderTopColor: "#dce4df", paddingTop: 7, color: "#6b7e78", fontSize: 7 }, total: { marginTop: 12, alignSelf: "flex-end", width: 190, flexDirection: "row", justifyContent: "space-between", fontWeight: 700 } });
const money = (value: number) => `N$ ${value.toFixed(2)}`;
const masked = (value?: string | null) => !value ? "Not captured" : value.length <= 4 ? "••••" : `${"•".repeat(Math.min(8, value.length - 4))}${value.slice(-4)}`;

export function ClaimStatementDocument({ claim, practice }: { claim: any; practice: any }) {
  let membership: Record<string, any> = {};
  if (claim.membershipDetailSnapshot) { try { membership = JSON.parse(claim.membershipDetailSnapshot); } catch { membership = {}; } }
  let patient: Record<string, any> = claim.patient || {};
  let provider: Record<string, any> = {};
  let practiceSnapshot: Record<string, any> = practice || {};
  if (claim.patientSnapshot) { try { patient = JSON.parse(claim.patientSnapshot); } catch { /* fall back to current patient for legacy claims */ } }
  if (claim.providerSnapshot) { try { provider = JSON.parse(claim.providerSnapshot); } catch { provider = {}; } }
  if (claim.practiceSnapshot) { try { practiceSnapshot = JSON.parse(claim.practiceSnapshot); } catch { /* fall back to current settings for legacy claims */ } }
  return <Document title={`Medical Aid Claim Statement ${claim.claimNumber}`} author={practice.practiceName}><Page size="A4" style={s.page}>
    <View style={s.header}><View><Text style={s.brand}>{(practiceSnapshot.practiceName || practice.practiceName).toUpperCase()}</Text><Text style={s.muted}>Practice no: {claim.practiceNumber}{"\n"}{practiceSnapshot.address || practice.address}{"\n"}{practiceSnapshot.phone || practice.claimPhone || practice.phone}</Text></View><View><Text style={s.title}>MEDICAL AID{`\n`}CLAIM STATEMENT</Text><Text style={[s.muted, { textAlign: "right" }]}>{claim.claimNumber}{"\n"}{claim.isResubmission ? "Resubmission" : "First submission"} · {claim.status}</Text></View></View>
    <View style={s.block}><View><Text style={{ fontWeight: 700 }}>PATIENT</Text><Text>{patient.fullName || "Not captured"}{"\n"}DOB: {patient.dateOfBirth ? new Date(patient.dateOfBirth).toLocaleDateString("en-NA") : "Not captured"}{"\n"}Patient: {patient.patientNumber || "Not captured"}</Text></View><View><Text style={{ fontWeight: 700 }}>MEMBERSHIP</Text><Text>{membership.fund || claim.medicalAidSnapshot || "Not captured"}{"\n"}Membership: {masked(membership.membershipNumber || claim.membershipSnapshot)}{"\n"}Dependant: {membership.dependantCode || claim.dependantSnapshot || "Not captured"}</Text></View><View><Text style={{ fontWeight: 700 }}>SERVICE</Text><Text>{claim.serviceDateFrom?.toLocaleDateString("en-NA")} to {claim.serviceDateTo?.toLocaleDateString("en-NA")}{"\n"}Provider: {provider.name || claim.practitioner}{"\n"}Registration: {provider.registrationNumber || "Not captured"}{"\n"}Type: {claim.claimType.replaceAll("_", " ")}</Text></View></View>
    <View style={s.section}><Text style={s.sectionTitle}>Claim lines</Text><View style={[s.row, { fontWeight: 700 }]}><Text style={s.code}>Date</Text><Text style={s.code}>Procedure</Text><Text style={s.wide}>Description</Text><Text style={s.code}>ICD-10</Text><Text style={s.cell}>Qty</Text><Text style={s.cell}>Amount</Text></View>{claim.lines.map((line: any) => <View style={s.row} key={line.id} wrap={false}><Text style={s.code}>{line.serviceDate?.toLocaleDateString("en-NA")}</Text><Text style={s.code}>{line.tariffCode}</Text><Text style={s.wide}>{line.description}{line.nappiCode ? `\nNAPPI: ${line.nappiCode}` : ""}</Text><Text style={s.code}>{line.diagnosisCodes.map((code: any) => code.codeSnapshot).join(", ")}</Text><Text style={s.cell}>{line.quantity}</Text><Text style={s.cell}>{money(line.claimed)}</Text></View>)}</View>
    <View style={s.total}><Text>Total claimed</Text><Text>{money(claim.amountSubmitted)}</Text></View>
    <View style={s.section}><Text style={s.sectionTitle}>Consent and authorisation</Text><Text style={s.muted}>ICD-10 disclosure consent: {claim.consentSnapshot ? "Captured" : "Not captured"}{"\n"}Authorised signatory: {practice.signatureName}, {practice.signatureTitle}{"\n"}Generated: {new Date().toLocaleDateString("en-NA")}</Text></View>
    <Text style={s.footer}>{practice.practiceName} · Medical Aid Claim Statement · Generated securely from the practice management system.</Text>
  </Page></Document>;
}

export function BatchDocument({ batch, practice, kind }: { batch: any; practice: any; kind: "COVER" | "MANIFEST" }) {
  return <Document title={`${kind === "COVER" ? "Medical Aid Batch Cover Sheet" : "Medical Aid Batch Manifest"} ${batch.reference}`} author={practice.practiceName}><Page size="A4" style={s.page}>
    <View style={s.header}><View><Text style={s.brand}>{practice.practiceName.toUpperCase()}</Text><Text style={s.muted}>Practice no: {practice.practiceNumber}{"\n"}{practice.address}</Text></View><View><Text style={s.title}>{kind === "COVER" ? "MEDICAL AID BATCH\nCOVER SHEET" : "MEDICAL AID BATCH\nMANIFEST"}</Text><Text style={[s.muted, { textAlign: "right" }]}>{batch.reference}</Text></View></View>
    <View style={s.block}><View><Text style={{ fontWeight: 700 }}>FUND</Text><Text>{batch.medicalAidName}</Text></View><View><Text style={{ fontWeight: 700 }}>SUBMISSION</Text><Text>{batch.submissionMethod || "Not selected"}{"\n"}{batch.submissionType.replaceAll("_", " ")}</Text></View><View><Text style={{ fontWeight: 700 }}>CLAIMS</Text><Text>{batch.totalClaims} attached{"\n"}{money(batch.totalAmount)}</Text></View><View><Text style={{ fontWeight: 700 }}>SERVICE DATES</Text><Text>{batch.serviceDateFrom?.toLocaleDateString("en-NA")} to {batch.serviceDateTo?.toLocaleDateString("en-NA")}</Text></View></View>
    {kind === "COVER" ? <View style={s.section}><Text style={s.sectionTitle}>Service provider details</Text><Text>Practice name: {practice.practiceName}{"\n"}Practice number: {practice.practiceNumber}{"\n"}Contact person: {practice.claimContactName || "Not configured"}{"\n"}Telephone: {practice.claimPhone || practice.phone}{"\n"}Date submitted: {batch.submittedAt?.toLocaleDateString("en-NA") || "Not submitted"}{"\n"}Submission reference: {batch.submissionReference || "Not captured"}</Text><View style={{ height: 90, marginTop: 24, borderWidth: 1, borderColor: "#b8c8c1", padding: 10 }}><Text style={s.muted}>PRACTICE STAMP / CLAIMS RECEIVED</Text></View></View> : <View style={s.section}><Text style={s.sectionTitle}>Claims</Text><View style={[s.row, { fontWeight: 700 }]}><Text style={s.code}>Reference</Text><Text style={s.wide}>Patient</Text><Text style={s.code}>Membership</Text><Text style={s.code}>Service date</Text><Text style={s.code}>ICD-10</Text><Text style={s.cell}>Amount</Text></View>{batch.items.map((item: any) => <View style={s.row} key={item.claim.id} wrap={false}><Text style={s.code}>{item.claim.claimNumber}</Text><Text style={s.wide}>{item.claim.patient.fullName}</Text><Text style={s.code}>{masked(item.claim.membershipSnapshot)}</Text><Text style={s.code}>{item.claim.serviceDateFrom?.toLocaleDateString("en-NA")}</Text><Text style={s.code}>{item.claim.lines[0]?.diagnosisCodes.find((code: any) => code.isPrimary)?.codeSnapshot || ""}</Text><Text style={s.cell}>{money(item.claim.amountSubmitted)}</Text></View>)}</View>}
    <Text style={s.footer}>{practice.practiceName} · {kind === "COVER" ? "Medical Aid Batch Cover Sheet" : "Medical Aid Batch Manifest"} · This is a practice-generated document, not an official fund form.</Text>
  </Page></Document>;
}
