import path from "node:path";
import { Document, Font, Page, StyleSheet, Text, View } from "@react-pdf/renderer";
import type { Invoice, InvoiceLine, Patient, PracticeSetting } from "@prisma/client";
type Data=Invoice&{patient:Patient;lines:InvoiceLine[]};

const onestPath=path.join(process.cwd(),"public/fonts/Onest-Variable.ttf");
Font.register({family:"Onest",fonts:[{src:onestPath,fontWeight:400},{src:onestPath,fontWeight:700}]});
Font.register({family:"Allura",src:path.join(process.cwd(),"public/fonts/Allura-Regular.ttf")});

const s=StyleSheet.create({page:{fontFamily:"Onest",fontSize:9,padding:38,color:"#18332d"},header:{flexDirection:"row",justifyContent:"space-between",paddingBottom:18,borderBottomWidth:1,borderBottomColor:"#cbd7d1"},brand:{fontSize:18,fontWeight:700,color:"#1f5a4c"},muted:{color:"#60736d",lineHeight:1.5},title:{fontSize:24,fontWeight:700,textAlign:"right"},block:{marginTop:20,padding:12,backgroundColor:"#f3f6f4",flexDirection:"row",justifyContent:"space-between"},table:{marginTop:20},row:{flexDirection:"row",borderBottomWidth:1,borderBottomColor:"#e4e9e6",paddingVertical:8},desc:{width:"43%"},cell:{width:"14%",textAlign:"right"},total:{flexDirection:"row",justifyContent:"flex-end",gap:20,paddingTop:7},signature:{fontFamily:"Allura",fontSize:25,marginTop:12,marginBottom:2},footer:{position:"absolute",bottom:32,left:38,right:38,borderTopWidth:1,borderTopColor:"#dce4df",paddingTop:10,color:"#647871",fontSize:8}});
export function InvoiceDocument({invoice,practice}:{invoice:Data;practice:PracticeSetting}){const fmt=(n:number)=>`N$ ${n.toFixed(2)}`;return <Document title={`Invoice ${invoice.number}`} author={practice.practiceName}><Page size="A4" style={s.page}><View style={s.header}><View><Text style={s.brand}>{practice.practiceName.toUpperCase()}</Text><Text style={s.muted}>{practice.doctorName}{"\n"}Practice no: {practice.practiceNumber}{"\n"}{practice.address}{"\n"}{practice.phone} · {practice.email}</Text></View><View><Text style={s.title}>INVOICE</Text><Text style={[s.muted,{textAlign:"right"}]}>{invoice.number}{"\n"}Issued {invoice.issueDate.toLocaleDateString("en-NA")}{"\n"}Status: {invoice.status}</Text></View></View><View style={s.block}><View><Text>PATIENT</Text><Text style={{fontWeight:700,marginTop:5}}>{invoice.patient.fullName}</Text><Text>{invoice.patient.patientNumber} · {invoice.patient.phone}</Text></View><View><Text style={{textAlign:"right"}}>PAYMENT RESPONSIBILITY</Text><Text style={{fontWeight:700,textAlign:"right",marginTop:5}}>{invoice.responsibility.replaceAll("_"," ")}</Text></View></View><View style={s.table}><View style={[s.row,{fontWeight:700}]}><Text style={s.desc}>Description</Text><Text style={s.cell}>Code</Text><Text style={s.cell}>Qty</Text><Text style={s.cell}>Rate</Text><Text style={s.cell}>Total</Text></View>{invoice.lines.map(line=><View key={line.id} style={s.row} wrap={false}><Text style={s.desc}>{line.description}</Text><Text style={s.cell}>{line.tariffCode||"—"}</Text><Text style={s.cell}>{line.quantity}</Text><Text style={s.cell}>{fmt(line.rate)}</Text><Text style={s.cell}>{fmt(line.total)}</Text></View>)}</View><View style={{marginTop:18}}><View style={s.total}><Text>Subtotal</Text><Text style={{width:85,textAlign:"right"}}>{fmt(invoice.subtotal)}</Text></View><View style={s.total}><Text>Medical aid responsibility</Text><Text style={{width:85,textAlign:"right"}}>{fmt(invoice.medicalAidResponsibility)}</Text></View><View style={s.total}><Text>Patient responsibility</Text><Text style={{width:85,textAlign:"right"}}>{fmt(invoice.patientResponsibility)}</Text></View><View style={[s.total,{fontWeight:700,fontSize:12,borderTopWidth:1,borderTopColor:"#18332d",marginTop:7,paddingTop:10}]}><Text>Balance due</Text><Text style={{width:85,textAlign:"right"}}>{fmt(invoice.total-invoice.patientPaid-invoice.medicalAidPaid)}</Text></View></View><View style={{marginTop:38}}><Text>Authorised signatory</Text><Text style={s.signature}>{practice.signatureName}</Text><Text>{practice.signatureTitle}</Text></View><View style={s.footer}><Text>{practice.practiceName} · {practice.address} · {practice.phone}</Text><Text style={{marginTop:4}}>This document was generated securely from the practice management system. Page 1</Text></View></Page></Document>}
