import {NextResponse} from "next/server";
import {z} from "zod";
import {requirePermission} from "@/lib/auth";
import {missingClaimInformation} from "@/lib/claims";
import {db} from "@/lib/db";
import {ref} from "@/lib/utils";
const getSession=()=>requirePermission("MANAGE_CLAIMS");
export async function POST(request:Request){const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorised"},{status:401});const parsed=z.object({appointmentId:z.string()}).safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Appointment is required"},{status:400});const a=await db.appointment.findUnique({where:{id:parsed.data.appointmentId},include:{patient:{include:{memberships:{where:{current:true},include:{medicalAid:true}}}}}});if(!a||a.status!=="COMPLETED")return NextResponse.json({error:"Only completed consultations can become claims."},{status:409});const membership=a.patient.memberships[0],practice=await db.practiceSetting.findUnique({where:{id:"practice"}});const claim=await db.$transaction(async tx=>{const created=await tx.claim.create({data:{claimNumber:ref("CLM"),appointmentId:a.id,patientId:a.patientId,consultationDate:a.startAt||new Date(),practitioner:practice?.doctorName||"",practiceNumber:practice?.practiceNumber||"",medicalAidSnapshot:membership?.medicalAid?.name||membership?.customFundName||null,membershipSnapshot:membership?.membershipNumber||null,principalSnapshot:membership?.principalName||null,dependantSnapshot:membership?.dependantCode||null,planSnapshot:membership?.plan||null,status:"MISSING_INFORMATION"}});await tx.activityLog.create({data:{userId:session.id,action:"CLAIM_CREATED",entityType:"Claim",entityId:created.id,summary:`Claim ${created.claimNumber} created from ${a.reference}`}});return created;});return NextResponse.json(claim,{status:201});}
export async function PATCH(request:Request){const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorised"},{status:401});const parsed=z.object({id:z.string(),primaryDiagnosis:z.string().min(2),primaryIcd10:z.string().min(3),lines:z.array(z.object({tariffCode:z.string().min(1),description:z.string().min(2),icd10:z.string().min(3),quantity:z.number().positive(),rate:z.number().nonnegative()})).min(1)}).safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Claim lines are incomplete."},{status:400});const result=await db.$transaction(async tx=>{await tx.claimLine.deleteMany({where:{claimId:parsed.data.id}});const amount=parsed.data.lines.reduce((n,l)=>n+l.quantity*l.rate,0);const claim=await tx.claim.update({where:{id:parsed.data.id},data:{primaryDiagnosis:parsed.data.primaryDiagnosis,primaryIcd10:parsed.data.primaryIcd10,amountSubmitted:amount,lines:{create:parsed.data.lines.map(l=>({...l,claimed:l.quantity*l.rate}))}},include:{lines:true}});const missing=missingClaimInformation(claim);return tx.claim.update({where:{id:claim.id},data:{status:missing.length?"MISSING_INFORMATION":"READY_FOR_REVIEW"}})});return NextResponse.json(result);}
