import {NextResponse} from "next/server";
import {z} from "zod";
import {requirePermission} from "@/lib/auth";
import {db} from "@/lib/db";
import {ref} from "@/lib/utils";
const getSession=()=>requirePermission("MANAGE_FINANCE");
export async function POST(request:Request){const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorised"},{status:401});const parsed=z.object({patientId:z.string(),appointmentId:z.string().optional(),responsibility:z.string(),patientResponsibility:z.number().nonnegative(),medicalAidResponsibility:z.number().nonnegative(),lines:z.array(z.object({description:z.string().min(2),tariffCode:z.string().optional(),quantity:z.number().positive(),rate:z.number().nonnegative(),patientPortion:z.number().nonnegative(),medicalAidPortion:z.number().nonnegative()})).min(1)}).safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Invoice details are incomplete."},{status:400});const total=parsed.data.lines.reduce((n,l)=>n+l.quantity*l.rate,0);if(Math.abs(total-parsed.data.patientResponsibility-parsed.data.medicalAidResponsibility)>.01)return NextResponse.json({error:"Patient and medical-aid portions must equal the invoice total."},{status:400});const invoice=await db.$transaction(async tx=>{const created=await tx.invoice.create({data:{number:ref("INV"),patientId:parsed.data.patientId,appointmentId:parsed.data.appointmentId||null,responsibility:parsed.data.responsibility,subtotal:total,total,patientResponsibility:parsed.data.patientResponsibility,medicalAidResponsibility:parsed.data.medicalAidResponsibility,lines:{create:parsed.data.lines.map(l=>({...l,total:l.quantity*l.rate}))}}});await tx.activityLog.create({data:{userId:session.id,action:"INVOICE_CREATED",entityType:"Invoice",entityId:created.id,summary:`Draft invoice ${created.number} created`}});return created});return NextResponse.json(invoice,{status:201});}

export async function PATCH(request:Request){const session=await getSession();if(!session)return NextResponse.json({error:"Unauthorised"},{status:401});const parsed=z.object({action:z.literal("VOID"),id:z.string(),reason:z.string().trim().min(3).max(400)}).safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"A void reason is required."},{status:400});try{const invoice=await db.$transaction(async tx=>{const current=await tx.invoice.findUnique({where:{id:parsed.data.id}});if(!current)throw new Error("NOT_FOUND");if(current.status!=="DRAFT"||current.patientPaid+current.medicalAidPaid>0)throw new Error("NOT_VOIDABLE");const updated=await tx.invoice.update({where:{id:current.id},data:{status:"VOID",voidedAt:new Date(),voidReason:parsed.data.reason,voidedByUserId:session.id}});await tx.generatedDocument.updateMany({where:{invoiceId:current.id,status:"ISSUED"},data:{status:"REVOKED"}});await tx.activityLog.create({data:{userId:session.id,action:"INVOICE_VOIDED",entityType:"Invoice",entityId:current.id,summary:`Invoice ${current.number} voided: ${parsed.data.reason}`}});return updated});return NextResponse.json(invoice)}catch(error){if(error instanceof Error&&error.message==="NOT_FOUND")return NextResponse.json({error:"Invoice not found."},{status:404});if(error instanceof Error&&error.message==="NOT_VOIDABLE")return NextResponse.json({error:"Only unpaid draft invoices can be voided."},{status:409});return NextResponse.json({error:"Could not void invoice."},{status:500})}}
