import type { Metadata } from "next";
export const metadata:Metadata={title:"Privacy and practice policies"};
const policies=[
  ["Privacy and confidentiality","Mondesa Health collects only the personal, contact, appointment, medical-aid and billing information needed to arrange care, maintain clinical and financial records, communicate with you and meet professional obligations. Access is limited according to staff role. Sensitive identifiers are masked in general views."],
  ["Booking consent","Submitting a booking authorises the practice to use the information provided to identify you, arrange the appointment and contact you using your chosen channel. Please provide only a short reason for your visit; detailed clinical information should be discussed privately with your practitioner."],
  ["Medical disclaimer and emergencies","Website information is general and does not replace an examination or professional medical advice. Online booking is not monitored as an emergency service. For an emergency in Namibia, call 112 or attend the nearest emergency department."],
  ["Cancellation and late arrival","Please give at least four hours’ notice when you cannot attend. Late arrival may shorten the consultation or require rescheduling so that other patients are not delayed. The practice may confirm any applicable fee before it is charged."],
  ["Electronic communication","WhatsApp, SMS and email may be used for administrative messages, reminders, secure document links and appointment changes when you select them. Avoid sending detailed clinical information through ordinary messages. Secure links expire and should not be forwarded."],
  ["Data retention","Patient, appointment, billing, claim and audit records are retained for the period required by applicable Namibian law, professional obligations and legitimate practice administration. Issued financial documents and audit entries are corrected by traceable adjustment rather than silent deletion."],
];
export default function Policies(){return <main><section style={{background:"#f7f4ed",padding:"80px 0"}}><div className="container" style={{maxWidth:850}}><div className="eyebrow">Privacy & policies</div><h1 className="display" style={{fontSize:"clamp(3.2rem,7vw,6rem)",margin:"18px 0"}}>Clear terms, in plain language.</h1><p style={{fontSize:18,lineHeight:1.7,color:"#5e716b"}}>These policies explain how online booking and practice communication work. Final retention periods and practice-specific fees should be reviewed by the owner’s legal and clinical advisers before launch.</p></div></section><section className="section"><div className="container" style={{maxWidth:850,display:"grid",gap:35}}>{policies.map(([title,text])=><article key={title} style={{borderBottom:"1px solid #dce4df",paddingBottom:30}}><h2 style={{fontSize:29,letterSpacing:"-.035em",marginTop:0}}>{title}</h2><p style={{lineHeight:1.8,color:"#5f736c"}}>{text}</p></article>)}</div></section></main>}
