import { createHash } from "crypto";
import { addMinutes } from "date-fns";
import { NextResponse } from "next/server";
import { z } from "zod";
import { getSession } from "@/lib/auth";
import { db } from "@/lib/db";
import { availableSlots } from "@/lib/slots";
import { ref } from "@/lib/utils";
export async function POST(request:Request){const session=await getSession();if(!session)return NextResponse.json({error:"Your session has expired."},{status:401});const parsed=z.object({patientId:z.string().min(1),date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),time:z.string().regex(/^\d{2}:\d{2}$/),reason:z.string().trim().min(2).max(200),notes:z.string().trim().max(500).optional()}).safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||"Check the appointment details."},{status:400});const {patientId,date,time,reason,notes}=parsed.data;const slots=await availableSlots(date);if(!slots.includes(time))return NextResponse.json({error:"That time is no longer available."},{status:409});const [patient,rule]=await Promise.all([db.patient.findUnique({where:{id:patientId}}),db.availabilityRule.findUnique({where:{weekday:new Date(`${date}T00:00:00`).getDay()}})]);if(!patient)return NextResponse.json({error:"Patient record not found."},{status:404});const startAt=new Date(`${date}T${time}:00`);try{const appointment=await db.$transaction(async tx=>{const created=await tx.appointment.create({data:{reference:ref("APT"),patientId,startAt,endAt:addMinutes(startAt,rule?.durationMinutes||30),preferredDate:new Date(`${date}T00:00:00`),status:"CONFIRMED",bookingMode:"AVAILABLE_TIME",source:"STAFF",reason,internalNote:notes||null,createdById:session.id}});await tx.activityLog.create({data:{userId:session.id,action:"APPOINTMENT_CREATED",entityType:"Appointment",entityId:created.id,summary:`Staff appointment ${created.reference} created for ${patient.fullName}`}});return created;});return NextResponse.json({reference:appointment.reference},{status:201});}catch(error){if(error instanceof Error&&error.message.includes("Unique constraint"))return NextResponse.json({error:"That time is no longer available."},{status:409});return NextResponse.json({error:"Could not create the appointment."},{status:500});}}
export async function PATCH(request:Request){const parsed=z.object({token:z.string().min(32),action:z.enum(["ACCEPT_RESCHEDULE","REQUEST_CHANGE","CANCEL"]),reason:z.string().max(400).optional()}).safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"This request is invalid."},{status:400});const link=await db.secureLink.findUnique({where:{tokenHash:createHash("sha256").update(parsed.data.token).digest("hex")},include:{appointment:true}});if(!link||link.expiresAt<new Date())return NextResponse.json({error:"This secure link is invalid or has expired."},{status:403});const status=parsed.data.action==="CANCEL"?"CANCELLED":parsed.data.action==="ACCEPT_RESCHEDULE"?"RESCHEDULED":"REVIEW_REQUIRED";await db.$transaction([db.appointment.update({where:{id:link.appointmentId},data:{status,notes:parsed.data.reason||link.appointment.notes}}),db.activityLog.create({data:{action:parsed.data.action==="CANCEL"?"APPOINTMENT_CANCELLED":"APPOINTMENT_RESPONSE",entityType:"Appointment",entityId:link.appointmentId,summary:`Patient response via secure link: ${parsed.data.action}`,beforeJson:JSON.stringify({status:link.appointment.status}),afterJson:JSON.stringify({status,reason:parsed.data.reason})}})]);return NextResponse.json({message:status==="CANCELLED"?"Your appointment has been cancelled.":"Your response has been sent to Mondesa Health."});}
