"use client";

import { useMemo, useState } from "react";
import { Download, Search } from "lucide-react";
import { useRouter } from "next/navigation";
import toast from "react-hot-toast";
import { CustomSelect } from "@/components/ui/custom-select";
import { DatePicker } from "@/components/ui/date-picker";
import { PlatformDialog } from "@/components/ui/platform-dialog";
import { StatusBadge } from "@/components/ui/status-badge";

type Row = { practiceId: string; practice: string; status: string; subscriptionId: string | null; planId: string; plan: string; renewalDate: string; graceUntil: string | null; paid: number; internalNotes: string };
type Payment = { id: string; practice: string; plan: string; amount: number; paidAt: string; reference: string | null };
export function PlatformBillingManager({ rows, plans, payments, canManage, canRecord }: { rows: Row[]; plans: { id: string; name: string }[]; payments: Payment[]; canManage: boolean; canRecord: boolean }) {
  const router = useRouter();
  const [editing, setEditing] = useState<Row | null>(null);
  const [recording, setRecording] = useState<Row | null>(null);
  const [status, setStatus] = useState("ACTIVE");
  const [planId, setPlanId] = useState("");
  const [renewalDate, setRenewalDate] = useState("");
  const [query, setQuery] = useState("");
  const [statusFilter, setStatusFilter] = useState("");
  const [saving, setSaving] = useState(false);
  const visible = rows.filter((row) => (!statusFilter || row.status === statusFilter) && `${row.practice} ${row.plan}`.toLowerCase().includes(query.trim().toLowerCase()));
  const summary = useMemo(() => ({ revenue: payments.reduce((total, payment) => total + payment.amount, 0), active: rows.filter((row) => row.status === "ACTIVE").length, overdue: rows.filter((row) => row.status === "OVERDUE").length, suspended: rows.filter((row) => row.status === "SUSPENDED").length }), [payments, rows]);
  function edit(row: Row) { setEditing(row); setStatus(row.status); setPlanId(row.planId); setRenewalDate(row.renewalDate); }
  async function request(method: "PATCH" | "POST", body: object, message: string) { setSaving(true); const toastId = toast.loading(message); try { const response = await fetch("/api/platform/subscriptions", { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); toast.success("Platform billing updated", { id: toastId }); setEditing(null); setRecording(null); router.refresh(); } catch (error) { toast.error(error instanceof Error ? error.message : "Could not update billing", { id: toastId }); } finally { setSaving(false); } }
  function exportPayments() { const esc = (value: string) => `"${value.replaceAll('"','""')}"`; const csv = ["Paid at,Practice,Plan,Amount NAD,Reference", ...payments.map((payment) => [payment.paidAt, payment.practice, payment.plan, payment.amount.toFixed(2), payment.reference || ""].map((value) => esc(String(value))).join(","))].join("\n"); const url = URL.createObjectURL(new Blob([csv], { type: "text/csv" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `mondesa-platform-payments-${new Date().toISOString().slice(0,10)}.csv`; anchor.click(); URL.revokeObjectURL(url); }
  return <>
    <div className="dashboard-stats"><div className="card dashboard-stat"><span className="dashboard-stat-label">Recorded subscription revenue</span><b className="dashboard-stat-value">N${summary.revenue.toFixed(2)}</b></div><div className="card dashboard-stat"><span className="dashboard-stat-label">Active subscriptions</span><b className="dashboard-stat-value">{summary.active}</b></div><div className="card dashboard-stat"><span className="dashboard-stat-label">Overdue</span><b className="dashboard-stat-value">{summary.overdue}</b></div><div className="card dashboard-stat"><span className="dashboard-stat-label">Suspended</span><b className="dashboard-stat-value">{summary.suspended}</b></div></div>
    <div className="manager-toolbar platform-filter-toolbar"><div className="search-box"><Search size={17}/><input className="input" aria-label="Search billing" placeholder="Search practice or plan" value={query} onChange={(event) => setQuery(event.target.value)}/></div><CustomSelect value={statusFilter} onChange={setStatusFilter} options={[{ value: "", label: "All statuses" }, ...["ACTIVE","OVERDUE","SUSPENDED","CANCELLED"].map((value) => ({ value, label: value }))]}/></div>
    <section className="card dashboard-card panel-card table-panel"><div className="panel-heading"><div><h2>Practice subscriptions</h2><p>Manage plan assignment, renewal, and lifecycle status for each practice.</p></div></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Practice</th><th>Plan</th><th>Status</th><th>Renewal</th><th>Grace</th><th>Payments</th><th>Actions</th></tr></thead><tbody>{visible.map((row) => <tr key={row.practiceId}><td><b>{row.practice}</b></td><td>{row.plan || "Unassigned"}</td><td><StatusBadge value={row.status}/></td><td>{row.renewalDate ? new Date(row.renewalDate).toLocaleDateString("en-NA") : "—"}</td><td>{row.graceUntil ? new Date(row.graceUntil).toLocaleDateString("en-NA") : "—"}</td><td>N${row.paid.toFixed(2)}</td><td><div className="table-actions">{canManage && <button className="btn btn-light" onClick={() => edit(row)}>Manage</button>}{canRecord && row.subscriptionId && <button className="btn btn-light" onClick={() => setRecording(row)}>Record payment</button>}</div></td></tr>)}</tbody></table></div>{!visible.length && <div className="dashboard-empty"><h3>No matching subscriptions</h3><p>Change the search or status filter.</p></div>}</section>
    <section className="card dashboard-card panel-card table-panel platform-ledger"><div className="panel-heading"><div><h2>Payment ledger</h2><p>Subscription payments recorded by authorised platform finance users.</p></div><button className="btn btn-light" onClick={exportPayments} disabled={!payments.length}><Download size={16}/>Export CSV</button></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Date</th><th>Practice</th><th>Plan</th><th>Reference</th><th>Amount</th></tr></thead><tbody>{payments.slice(0,100).map((payment) => <tr key={payment.id}><td>{new Date(payment.paidAt).toLocaleDateString("en-NA")}</td><td>{payment.practice}</td><td>{payment.plan}</td><td>{payment.reference || "—"}</td><td>N${payment.amount.toFixed(2)}</td></tr>)}</tbody></table></div>{!payments.length && <div className="dashboard-empty"><h3>No subscription payments</h3><p>Recorded payments will appear here.</p></div>}</section>
    <PlatformDialog open={Boolean(editing)} eyebrow="Platform billing" title={editing?.practice || "Manage subscription"} description="Overdue status starts the selected plan’s grace period. Suspension blocks new writes while preserving reads and exports." onClose={() => setEditing(null)} actions={<><button className="btn btn-light" onClick={() => setEditing(null)}>Cancel</button><button form="subscription-edit-form" className="btn btn-primary" disabled={saving || !planId}>Save subscription</button></>}><form id="subscription-edit-form" className="form-grid" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (editing) request("PATCH", { practiceId: editing.practiceId, status, planId, renewalDate: renewalDate ? new Date(`${renewalDate}T12:00:00Z`).toISOString() : undefined, internalNotes: form.get("internalNotes") }, "Updating subscription…"); }}><label className="field"><span>Plan</span><CustomSelect value={planId} onChange={setPlanId} options={plans.map((plan) => ({ value: plan.id, label: plan.name }))}/></label><label className="field"><span>Status</span><CustomSelect value={status} onChange={setStatus} options={["ACTIVE","OVERDUE","SUSPENDED","CANCELLED"].map((value) => ({ value, label: value }))}/></label><label className="field"><span>Renewal date</span><DatePicker value={renewalDate} onChange={setRenewalDate} ariaLabel="Renewal date"/></label><label className="field field-span-2"><span>Internal billing notes</span><textarea className="input" name="internalNotes" defaultValue={editing?.internalNotes}/></label></form></PlatformDialog>
    <PlatformDialog open={Boolean(recording)} eyebrow="Subscription payment" title={recording ? `Record payment · ${recording.practice}` : "Record payment"} onClose={() => setRecording(null)} actions={<><button className="btn btn-light" onClick={() => setRecording(null)}>Cancel</button><button form="subscription-payment-form" className="btn btn-primary" disabled={saving}>Record payment</button></>}><form id="subscription-payment-form" className="form-grid" onSubmit={(event) => { event.preventDefault(); const form = new FormData(event.currentTarget); if (recording?.subscriptionId) request("POST", { subscriptionId: recording.subscriptionId, amount: Number(form.get("amount")), reference: form.get("reference") || undefined, method: form.get("method") || undefined, notes: form.get("notes") || undefined }, "Recording payment…"); }}><label className="field"><span>Amount (NAD)</span><input className="input" name="amount" type="number" min="0.01" step="0.01" required/></label><label className="field"><span>Reference</span><input className="input" name="reference"/></label><label className="field"><span>Method</span><input className="input" name="method" placeholder="EFT, cash, card…"/></label><label className="field field-span-2"><span>Notes</span><textarea className="input" name="notes"/></label></form></PlatformDialog>
  </>;
}
