"use client";
import { useState } from "react";
import { Clipboard, Mail, MessageCircle } from "lucide-react";
import toast from "react-hot-toast";
import { useRouter } from "next/navigation";

type Reminder = { id:string|null;appointmentId:string;appointmentStartAt:string;status:string;reference:string;patient:string;phone:string;whatsapp:string|null;email:string|null };
export function ReminderQueue({ reminders }: { reminders: Reminder[] }) {
  const router=useRouter();const[prepared,setPrepared]=useState<Record<string,{id:string;message:string;link:string;whatsapp:string|null;email:string|null}>>({});
  async function prepare(item:Reminder){try{const first=await fetch("/api/appointment-reminders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"PREPARE",appointmentId:item.appointmentId})});const reminder=await first.json();if(!first.ok)throw new Error(reminder.error);const response=await fetch("/api/appointments/share",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:item.appointmentId,kind:"REMINDER"})});const data=await response.json();if(!response.ok)throw new Error(data.error);setPrepared(current=>({...current,[item.appointmentId]:{id:reminder.id,...data}}));toast.success("Reminder message prepared; it has not been sent.")}catch(error){toast.error(error instanceof Error?error.message:"Could not prepare reminder")}}
  async function finish(item:Reminder,action:"MARK_SENT"|"DISMISS"){const id=prepared[item.appointmentId]?.id||item.id;if(!id&&action==="MARK_SENT")return toast.error("Prepare the reminder before marking it sent.");const response=await fetch("/api/appointment-reminders",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,id,appointmentId:item.appointmentId})});const data=await response.json();if(!response.ok)return toast.error(data.error);toast.success(action==="MARK_SENT"?"Reminder marked sent":"Reminder dismissed");router.refresh()}
  if(!reminders.length)return null;
  return <section className="card dashboard-card" style={{padding:20,marginBottom:18}}><div className="manager-toolbar"><div><h2>Reminder preparation queue</h2><p>{reminders.length} confirmed appointment{reminders.length===1?" is":"s are"} inside the reminder window. External apps do not confirm delivery.</p></div></div>{reminders.map(item=>{const draft=prepared[item.appointmentId];return <div className="blocked-row" key={item.appointmentId}><div><b>{item.patient} · {item.reference}</b><small>{new Date(item.appointmentStartAt).toLocaleString("en-NA")}</small>{draft&&<textarea className="input" value={draft.message} onChange={event=>setPrepared(current=>({...current,[item.appointmentId]:{...draft,message:event.target.value}}))}/>}</div><div className="table-actions"><button className="btn btn-light" onClick={()=>prepare(item)}>Prepare message</button>{draft?.whatsapp&&<a className="btn btn-primary" href={`${draft.whatsapp.split("?text=")[0]}?text=${encodeURIComponent(draft.message)}`} target="_blank" rel="noopener noreferrer"><MessageCircle size={15}/> WhatsApp</a>}{draft?.email&&<a className="btn btn-light" href={`${draft.email.split("&body=")[0]}&body=${encodeURIComponent(draft.message)}`}><Mail size={15}/> Email</a>}{draft&&<><button className="btn btn-light" onClick={()=>navigator.clipboard.writeText(draft.message).then(()=>toast.success("Message copied"))}><Clipboard size={15}/> Copy</button><button className="btn btn-light" onClick={()=>finish(item,"MARK_SENT")}>Mark sent</button></>}<button className="btn btn-light" onClick={()=>finish(item,"DISMISS")}>Dismiss</button></div></div>})}</section>
}
