import { createHash, randomBytes } from "crypto";
import { addDays } from "date-fns";
import { NextResponse } from "next/server";
import { z } from "zod";
import { requirePlatformOwner } from "@/lib/auth";
import { db } from "@/lib/db";
import { requestAuditInfo } from "@/lib/tenant";

const status = z.enum(["DRAFT","SUBMITTED","UNDER_REVIEW","APPROVED","ACTIVE","PAYMENT_OVERDUE","SUSPENDED","REJECTED","CLOSED"]);
const create = z.object({ name:z.string().trim().min(2).max(140), type:z.string().trim().min(2).max(80), ownerName:z.string().trim().min(2).max(120), ownerEmail:z.string().email(), registrationNumber:z.string().trim().max(100).optional(), licenceInformation:z.string().trim().max(500).optional(), phone:z.string().trim().max(30).optional(), whatsapp:z.string().trim().max(30).optional(), address:z.string().trim().max(300).optional(), town:z.string().trim().max(100).optional(), region:z.string().trim().max(100).optional(), description:z.string().trim().max(2000).optional(), status:status.default("DRAFT"), publicVisible:z.boolean().default(false), planId:z.string().optional() });
const update = create.partial().extend({ id:z.string(), suspensionReason:z.string().trim().max(1000).optional() });
const slugify=(value:string)=>value.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,60);
export async function POST(request:Request){const session=await requirePlatformOwner();if(!session)return NextResponse.json({error:"Platform-owner access is required."},{status:403});const parsed=create.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||"Check the practice details."},{status:400});const input=parsed.data;if(input.publicVisible&&!['APPROVED','ACTIVE'].includes(input.status))return NextResponse.json({error:"Only approved or active practices can be public."},{status:400});const rawToken=randomBytes(32).toString("base64url");const practice=await db.$transaction(async tx=>{let slug=slugify(input.name);if(await tx.practice.findUnique({where:{slug}}))slug=`${slug}-${randomBytes(3).toString("hex")}`;const created=await tx.practice.create({data:{slug,name:input.name,type:input.type,ownerName:input.ownerName,registrationNumber:input.registrationNumber,licenceInformation:input.licenceInformation,email:input.ownerEmail.toLowerCase(),phone:input.phone,whatsapp:input.whatsapp,address:input.address,town:input.town,region:input.region,description:input.description,status:input.status,publicVisible:input.publicVisible,activatedAt:input.status==="ACTIVE"?new Date():null,setting:{create:{id:`practice-${slug}`,practiceName:input.name,doctorName:input.ownerName,email:input.ownerEmail.toLowerCase(),phone:input.phone||"Pending configuration",whatsapp:input.whatsapp||input.phone||"Pending configuration",address:input.address||"Pending configuration"}},availabilityRules:{create:[1,2,3,4,5].map(weekday=>({weekday,active:true,openTime:"08:00",closeTime:"17:00",lunchStart:"13:00",lunchEnd:"14:00",durationMinutes:30}))}}});await tx.userInvitation.create({data:{practiceId:created.id,email:input.ownerEmail.toLowerCase(),name:input.ownerName,role:"OWNER",tokenHash:createHash("sha256").update(rawToken).digest("hex"),expiresAt:addDays(new Date(),7),invitedById:session.id}});if(input.planId)await tx.practiceSubscription.create({data:{practiceId:created.id,planId:input.planId,status:"ACTIVE",renewalDate:addDays(new Date(),30)}});await tx.activityLog.create({data:{userId:session.id,practiceId:created.id,action:"PRACTICE_CREATED",entityType:"Practice",entityId:created.id,summary:`Created practice ${created.name} and invited its owner`,requestInfo:requestAuditInfo(request)}});return created});return NextResponse.json({id:practice.id,inviteUrl:`/invite/${rawToken}`},{status:201})}
export async function PATCH(request:Request){const session=await requirePlatformOwner();if(!session)return NextResponse.json({error:"Platform-owner access is required."},{status:403});const parsed=update.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||"Check the practice changes."},{status:400});const {id,...input}=parsed.data;const current=await db.practice.findUnique({where:{id}});if(!current)return NextResponse.json({error:"Practice not found."},{status:404});if(input.publicVisible&&!['APPROVED','ACTIVE'].includes(input.status||current.status))return NextResponse.json({error:"Only approved or active practices can be public."},{status:400});const practice=await db.$transaction(async tx=>{const saved=await tx.practice.update({where:{id},data:{...input,activatedAt:input.status==="ACTIVE"&&!current.activatedAt?new Date():undefined,publicVisible:input.status&&!["APPROVED","ACTIVE"].includes(input.status)?false:input.publicVisible}});await tx.activityLog.create({data:{userId:session.id,practiceId:id,action:input.status==="SUSPENDED"?"PRACTICE_SUSPENDED":input.status==="ACTIVE"?"PRACTICE_APPROVED":"PRACTICE_UPDATED",entityType:"Practice",entityId:id,summary:`Updated practice ${saved.name}`,requestInfo:requestAuditInfo(request)}});return saved});return NextResponse.json({id:practice.id,status:practice.status})}
