import { createHash } from "crypto";
import { hash } from "bcryptjs";
import { NextResponse } from "next/server";
import { z } from "zod";
import { db } from "@/lib/db";
import { passwordSchema } from "@/lib/password";
import { roleDefaults } from "@/lib/permissions";
const tokenHash=(token:string)=>createHash("sha256").update(token).digest("hex");
export async function GET(_request:Request,{params}:{params:Promise<{token:string}>}){const{token}=await params;const invitation=await db.userInvitation.findFirst({where:{tokenHash:tokenHash(token),acceptedAt:null,expiresAt:{gt:new Date()}},include:{practice:{select:{name:true,status:true}}}});if(!invitation)return NextResponse.json({error:"This invitation is invalid or has expired."},{status:404});return NextResponse.json({name:invitation.name,email:invitation.email,practice:invitation.practice.name})}
export async function POST(request:Request,{params}:{params:Promise<{token:string}>}){const{token}=await params;const parsed=z.object({password:passwordSchema}).safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message||"Choose a secure password."},{status:400});const invitation=await db.userInvitation.findFirst({where:{tokenHash:tokenHash(token),acceptedAt:null,expiresAt:{gt:new Date()}}});if(!invitation)return NextResponse.json({error:"This invitation is invalid or has expired."},{status:404});try{await db.$transaction(async tx=>{const user=await tx.user.create({data:{name:invitation.name,email:invitation.email,passwordHash:await hash(parsed.data.password,12),role:invitation.role,permissions:JSON.stringify(roleDefaults[invitation.role as keyof typeof roleDefaults]||[]),practiceId:invitation.practiceId}});await tx.practiceUser.create({data:{practiceId:invitation.practiceId,userId:user.id,role:invitation.role,permissions:user.permissions}});await tx.userInvitation.update({where:{id:invitation.id},data:{acceptedAt:new Date()}});await tx.activityLog.create({data:{userId:user.id,practiceId:invitation.practiceId,action:"PRACTICE_INVITATION_ACCEPTED",entityType:"Practice",entityId:invitation.practiceId,summary:"Practice owner account activated"}})});return NextResponse.json({ok:true})}catch{return NextResponse.json({error:"An account already uses this email. Contact platform support."},{status:409})}}
