"use client";

import { Copy, Download, Loader2, Mail, MessageCircle, Share2, X } from "lucide-react";
import toast from "react-hot-toast";

export type DocumentShare = { link: string; message: string };

export function DocumentPreviewModal({ open, eyebrow, number, previewUrl, downloadUrl, onClose, onShare, secondaryAction }: { open: boolean; eyebrow: string; number: string; previewUrl: string; downloadUrl?: string; onClose: () => void; onShare?: () => void; secondaryAction?: React.ReactNode }) {
  if (!open) return null;
  return <div className="appointment-modal finance-preview-modal" role="dialog" aria-modal="true" aria-label={`${number} document preview`}><button className="appointment-modal-backdrop" aria-label="Close preview" onClick={onClose} /><div className="appointment-panel"><div className="appointment-panel-heading"><div><span className="eyebrow">{eyebrow}</span><h2>{number}</h2></div><button type="button" aria-label="Close" onClick={onClose}><X size={20} /></button></div><iframe className="finance-preview-frame" title={`Preview ${number}`} src={previewUrl} /><div className="appointment-panel-actions"><button className="btn btn-light" onClick={onClose}>Close</button>{secondaryAction}{downloadUrl && <a className="btn btn-light" href={downloadUrl} download><Download size={15} /> Download PDF</a>}{onShare && <button className="btn btn-primary" onClick={onShare}><Share2 size={15} /> Share</button>}</div></div></div>;
}

export function DocumentShareModal({ open, number, kind, share, patientPhone, patientWhatsapp, patientEmail, onMessageChange, onClose }: { open: boolean; number: string; kind: string; share: DocumentShare | null; patientPhone: string; patientWhatsapp: string | null; patientEmail: string | null; onMessageChange: (message: string) => void; onClose: () => void }) {
  if (!open) return null;
  const copyLink = async () => { if (!share) return; await navigator.clipboard.writeText(share.link); toast.success("Secure link copied"); };
  const copyMessage = async () => { if (!share) return; await navigator.clipboard.writeText(share.message); toast.success("Message copied"); };
  const title = `${kind} ${number}`;
  return <div className="appointment-modal" role="dialog" aria-modal="true" aria-label={`Share ${number}`}><button className="appointment-modal-backdrop" aria-label="Close share" onClick={onClose} /><div className="appointment-panel"><div className="appointment-panel-heading"><div><span className="eyebrow">Secure sharing</span><h2>Share {number}</h2><p>Review the message before opening a sharing option. Opening an app does not mark it delivered.</p></div><button type="button" aria-label="Close" onClick={onClose}><X size={20} /></button></div>{share ? <div className="appointment-form-grid"><div className="share-link-box dashboard-span-all"><b>Secure link</b><span>{share.link}</span></div><label className="field dashboard-span-all"><span>Message</span><textarea className="input share-message-preview" value={share.message} onChange={(event) => onMessageChange(event.target.value)} /></label><div className="share-actions dashboard-span-all"><a className="btn btn-primary" href={`https://wa.me/${(patientWhatsapp || patientPhone).replace(/\D/g, "")}?text=${encodeURIComponent(share.message)}`} target="_blank" rel="noopener noreferrer"><MessageCircle size={15} /> WhatsApp</a>{patientEmail && <a className="btn btn-light" href={`mailto:${encodeURIComponent(patientEmail)}?subject=${encodeURIComponent(`${title} - Mondesa Health`)}&body=${encodeURIComponent(share.message)}`}><Mail size={15} /> Email</a>}<button className="btn btn-light" onClick={copyMessage}><Copy size={15} /> Copy message</button><button className="btn btn-light" onClick={copyLink}><Copy size={15} /> Copy link</button>{"share" in navigator && <button className="btn btn-light" onClick={() => navigator.share({ title, text: share.message, url: share.link })}><Share2 size={15} /> More sharing options</button>}</div></div> : <div className="share-loading"><Loader2 className="toast-spinner" size={18} /> Creating secure link…</div>}</div></div>;
}
